services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  document_service:
    build: ./src/services/document_service
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    volumes:
      - ./uploads:/app/uploads

  document_processor_service:
    build: ./src/services/document_processor_service
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672

  address_analyzer_service:
    build: ./src/services/address_analyzer_service
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672

  result_processor_service:
    build: ./src/services/result_processor_service
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672

  ui:
    build: ./ui
    ports:
      - "8501:8501"
    depends_on:
      - document_service
      - result_processor_service
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
